# Generated by Django 5.0 on 2024-01-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='marrrital_status',
            new_name='marrital_status',
        ),
    ]
