# Generated by Django 5.0 on 2024-01-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_marrrital_status_kyc_marrital_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='marrital_status',
            new_name='marital_status',
        ),
    ]
