# Generated by Django 5.0 on 2024-01-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='nationality',
            field=models.CharField(choices=[('india', 'India'), ('nigeria', 'Nigeria'), ('united_kingdom', 'United Kingdom')], max_length=100),
        ),
    ]
