# Generated by Django 5.0 on 2024-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('master', 'Master'), ('visa', 'Visa'), ('verve', 'Verve')], default='master', max_length=20),
        ),
    ]
